### ISSUE TITLE
sample04にて、ロール名を変更するとエラーが発生

### ISSUE THREAD

**Issue by shizuko-m** [soars-jp/samples#15]
以下のROLE_NAMEをクラス名に合わせて変更すると、Exceptionが発生。
https://github.com/soars-jp/samples/blob/master/src/main/java/jp/soars/examples/sample04/TChildRole.java#L9
```
Exception in thread "main" java.lang.IllegalArgumentException: Error: Agent does not have ChildRole.
	at jp.soars.core.TObject.activateRole(TObject.java:95)
	at jp.soars.examples.sample04.TRecoveringFromSickRule.doIt(TRecoveringFromSickRule.java:46)
	at jp.soars.core.TRuleAggregator.executeRules(TRuleAggregator.java:363)
	at jp.soars.core.TRuleAggregator.executeStage(TRuleAggregator.java:228)
	at jp.soars.core.TModel.execute(TModel.java:134)
	at jp.soars.examples.sample04.TMain.main(TMain.java:112)
```

**Comment by kojima0615** [comment]
以下の場所でfBackRoleがstaticになっていたため発生したExceptionでした．
申し訳ございませんでした．
https://github.com/soars-jp/samples/blob/28657a9aae9d06f02eff660b032d026ceb2f88ae/src/main/java/jp/soars/examples/sample04/TRecoveringFromSickRule.java#L24

**Comment by shizuko-m** [comment]
対応ありがとうございます。
こちらでも動作確認できましたので、クローズさせていただきます。
（こちらでのクローズに問題あれば教えてください）
